name: fiu_csl_checkin
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  parse_server_sdk_flutter: ^7.0.1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.12
  get: ^4.3.8
  url_launcher: ^6.0.9
  image_picker: ^1.0.7
  mlkit_scanner: ^0.5.3
  ocr_scan_text: ^1.3.1
  google_mlkit_text_recognition: ^0.8.1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  qr_code_scanner: ^1.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/
  uses-material-design: true