name: fiu_csl_checkin
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  parse_server_sdk_flutter: ^7.0.1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.12
  url_launcher: ^6.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  qr_code_scanner: ^1.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/cart.png
    - assets/cslLabLogo.png
    - assets/devices.png
    - assets/fiu_roary.png
    - assets/logout.png
    - assets/undo.png
  uses-material-design: true